aliases: {}
creation_timestamp: 1779008088267
deployment_job_id: null
deployment_job_state: null
description: Modèle de classification — version optimisée
last_updated_timestamp: 1779456237554
name: mon_modele_production
workspace: default
