artifact_uri: file:///C:\Users\rayan\Desktop\ProjetML\Back\mlflow_runs/326793583795362966/aabbf10abd324fadbee11467fb964e2a/artifacts
end_time: 1779455043900
entry_point_name: ''
experiment_id: '326793583795362966'
lifecycle_stage: active
run_id: aabbf10abd324fadbee11467fb964e2a
run_name: dapper-loon-606
source_name: ''
source_type: 4
source_version: ''
start_time: 1779455030583
status: 3
tags: []
user_id: unknown
