artifact_uri: file:///C:\Users\rayan\Desktop\ProjetML\Back\mlflow_runs/326793583795362966/d8b7b3a147f3408e8e5b8168d9b58cc2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '326793583795362966'
lifecycle_stage: active
run_id: d8b7b3a147f3408e8e5b8168d9b58cc2
run_name: serious-kit-951
source_name: ''
source_type: 4
source_version: ''
start_time: 1779453881454
status: 1
tags: []
user_id: unknown
