creation_timestamp: 1779008820919
current_stage: None
deployment_job_state: null
description: ''
last_updated_timestamp: 1779008820919
model_id: m-cb3fe341c97c475089f39aa5a5af5654
name: mon_modele_production
run_id: 73e7ac0f1e0d4fae85b2143e780ae1bb
run_link: ''
source: models:/m-cb3fe341c97c475089f39aa5a5af5654
status: READY
status_message: null
storage_location: file:///C:\Users\rayan\Desktop\ProjetML\Back\mlflow_runs/326793583795362966/models/m-cb3fe341c97c475089f39aa5a5af5654/artifacts
user_id: null
version: 2
workspace: default
