artifact_uri: file:///C:\Users\rayan\Desktop\ProjetML\Back\mlflow_runs/326793583795362966/991f9263afd34b96aceacf768c76cbc6/artifacts
end_time: 1777974219663
entry_point_name: ''
experiment_id: '326793583795362966'
lifecycle_stage: active
run_id: 991f9263afd34b96aceacf768c76cbc6
run_name: luxuriant-chimp-224
source_name: ''
source_type: 4
source_version: ''
start_time: 1777974218122
status: 4
tags: []
user_id: rayan
