artifact_uri: file:///C:\Users\rayan\Desktop\ProjetML\Back\mlflow_runs/326793583795362966/40ff94d2ade048cdaf76f2b6d086050c/artifacts
end_time: 1779454283094
entry_point_name: ''
experiment_id: '326793583795362966'
lifecycle_stage: active
run_id: 40ff94d2ade048cdaf76f2b6d086050c
run_name: blushing-gnu-668
source_name: ''
source_type: 4
source_version: ''
start_time: 1779454185732
status: 3
tags: []
user_id: unknown
