artifact_uri: file:///C:\Users\rayan\Desktop\ProjetML\Back\mlflow_runs/326793583795362966/57e2b30d94474b44b7dfb8d517ff4d4d/artifacts
end_time: null
entry_point_name: ''
experiment_id: '326793583795362966'
lifecycle_stage: active
run_id: 57e2b30d94474b44b7dfb8d517ff4d4d
run_name: unleashed-ape-720
source_name: ''
source_type: 4
source_version: ''
start_time: 1779454642487
status: 1
tags: []
user_id: unknown
